### ISSUE TITLE
The given account is not owned by the executing program

### ISSUE THREAD

**Issue by spreadmycode** [samuelvanderwaal/solana-whitelist#1]
I have just build and deploy this contract.
But it shows that "The given account is not owned by the executing program" and failed.
It shows when calling `initialize ` function.
![image](https://user-images.githubusercontent.com/91585048/145738444-1a394c8d-549b-4f57-9db3-abf87cf9bb09.png)

Please help me.

**Comment by samuelvanderwaal** [comment]
This repo is just an example of how to make a whitelist using a 10 MB account created client side with Anchor's ZeroCopy macro, it's not intended to be fully working out-of-the-box. You'll need to put in your own program id instead of the one I have hardcoded in there.

**Comment by spreadmycode** [comment]
Hello @samuelvanderwaal .
Thanks for your reply.
I am a poor of Solana developer. So I don't understand your guide. So sorry about that.
I have just written my whole code (just I updated some part.) and please check and warm thanks let me know what part is wrong.
```
use anchor_lang::prelude::*;
use std::convert::TryInto;
use std::ops::DerefMut;

declare_id!("G9B3QBo3BJAbn37XmaBNN4ybjLXuiUSRxwgjGdyau85J");

const MAX_LEN: usize = 3000;

#[program]
pub mod whitelist {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> ProgramResult {
        let whitelist_state = &mut ctx.accounts.whitelist_state;
        let mut whitelist_data = ctx.accounts.whitelist_data.load_init()?;
        let data = whitelist_data.deref_mut();
        data.data = [Pubkey::default(); MAX_LEN];
        whitelist_state.counter = 0;
        Ok(())
    }

    pub fn add_whitelist_addresses(
        ctx: Context<AddWhitelistAddresses>,
        addresses: Vec<Pubkey>,
    ) -> ProgramResult {
        let whitelist_state = &mut ctx.accounts.whitelist_state;
        let mut whitelist_data = ctx.accounts.whitelist_data.load_mut()?;
        let mut data = whitelist_data.deref_mut();

        let length = addresses.len();
        let mut counter = whitelist_state.counter as usize;

        // Check that new addresses don't exceed remaining space
        if length + counter > MAX_LEN {
            return Ok(());
        }
        msg!("counter: {}", counter);
        let mut current_data: Vec<Pubkey> = Vec::new();
        // Fill with current data
        current_data.extend_from_slice(&data.data[0..counter]);
        counter += length;

        // Add new addresses
        current_data.extend_from_slice(&addresses);

        // Fill remaining data with default Pubkey
        for _ in counter..MAX_LEN {
            current_data.push(Pubkey::default());
        }
        msg!("current data: {:?}", current_data.len());

        // Update data
        let new_data: [Pubkey; MAX_LEN] = match current_data.try_into() {
            Ok(data) => data,
            Err(e) => {
                msg!("Error: {:?}", e);
                return Ok(())
            }
        };
        data.data = new_data;
        whitelist_state.counter = counter as u64;
        msg!("counter: {}", counter);

        Ok(())
    }

    pub fn reset_whitelist_counter(ctx: Context<ResetWhitelistCounter>) -> ProgramResult {
        let whitelist_state = &mut ctx.accounts.whitelist_state;
        whitelist_state.counter = 0;

        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(init, payer = user, space = 8 + 32 + 8)]
    pub whitelist_state: Account<'info, WhitelistState>,
    #[account(zero)]
    pub whitelist_data: AccountLoader<'info, WhitelistData>,
    #[account(mut)]
    pub user: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct AddWhitelistAddresses<'info> {
    #[account(mut)]
    pub whitelist_state: Account<'info, WhitelistState>,
    #[account(mut)]
    pub whitelist_data: AccountLoader<'info, WhitelistData>,
}

#[derive(Accounts)]
pub struct ResetWhitelistCounter<'info> {
    pub whitelist_state: Account<'info, WhitelistState>,
}

#[account]
pub struct WhitelistState {
    pub counter: u64,
}

#[account(zero_copy)]
pub struct WhitelistData {
    pub data: [Pubkey; 3000],
}
```

**Comment by spreadmycode** [comment]
You mean update the ```declare_id!("G9B3QBo3BJAbn37XmaBNN4ybjLXuiUSRxwgjGdyau85J");``` with my own deployed contract ID?

**Comment by samuelvanderwaal** [comment]
> You mean update the `declare_id!("G9B3QBo3BJAbn37XmaBNN4ybjLXuiUSRxwgjGdyau85J");` with my own deployed contract ID?

Yes, and also in the `client.js` file.

**Comment by spreadmycode** [comment]
```
Transaction simulation failed: Error processing Instruction 1: custom program error: 0xa7
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0xa7
    Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje consumed 10508 of 200000 compute units
    Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje failed: custom program error: 0xa7
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0xa7
    at Connection.sendEncodedTransaction (/home/work/cli-contract/node_modules/@solana/web3.js/src/connection.ts:3689:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/home/work/cli-contract/node_modules/@solana/web3.js/src/connection.ts:3649:20)
    at async Object.sendAndConfirmRawTransaction (/home/work/cli-contract/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/work/cli-contract/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeContract] (/home/work/cli-contract/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0xa7',
    'Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje consumed 10508 of 200000 compute units',
    'Program 94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje failed: custom program error: 0xa7'
  ]
}
(node:266455) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (/home/work/cli-contract/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as initializeContract] (/home/work/cli-contract/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:266455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:266455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I did but it shows this error.
I don't really understand Anchor's ZeroCopy macro working.
Please help me.

**Comment by spreadmycode** [comment]
I think this error same as before.
Even update id in contract source.
This is contract source.
```declare_id!("9pkYv3SvYfd51mh1v3vn1aX2WHepx7wZxsfxpmsNdFT7");```

This is client source.
```const PROGRAM_ID = new PublicKey('94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje');```

After ```solana deploy whitelist.so``` it returned ```94mweQHibXMVsQDmoHbXz1Sxpu9D9nxznf3movyFFWje```
So I use this address in client.

**Comment by spreadmycode** [comment]
I didn't find the way.
Same error 167 occurred every time.
It is splitting my head nowadays.
Please help me.

**Comment by samuelvanderwaal** [comment]
The only reason I pushed this repo was someone specifically wanted to see the example of how to do it, I have no plans to provide general Solana support on it, sorry, I'm just far too busy right now. That's why there's no README, instructions, etc. If you need help with Solana dev you should seek out the docs, and the various support Discords or find people on Twitter who are willing to help.

**Comment by spreadmycode** [comment]
Thanks.

**Comment by samuelvanderwaal** [comment]
> Thanks.

Anchord Discord: https://discord.gg/TnKjhVKM

Solana Discord: https://discord.gg/solana

Thanks for your understanding.
